const mongoose = require("mongoose");
const Product = require("./models/Product");

mongoose.connect("mongodb+srv://hkmathesh:u36INrIbXSVkTDMi@cluster0.fq2wn.mongodb.net/flipkartDB?retryWrites=true&w=majority");

const products = [ 
    // Mobiles
    {
        name: "iPhone 15 Pro",
        category: "mobiles",
        specifications: {
            storage: "256GB",
            display: "6.1-inch Super Retina XDR",
            camera: "48MP Main Camera",
            processor: "A17 Pro Chip",
            warranty: "1 Year Apple Warranty",
        },
        price: 129999,
        originalPrice: 139999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743511734/iphone_15_w6zhnw.jpg",
    },
    {
        name: "Samsung Galaxy S23 Ultra",
        category: "mobiles",
        specifications: {
            storage: "512GB",
            display: "6.8-inch Dynamic AMOLED 2X",
            camera: "200MP Main Camera",
            processor: "Snapdragon 8 Gen 2",
            warranty: "1 Year Samsung Warranty",
        },
        price: 124999,
        originalPrice: 134999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743518195/Samsung_Galaxy_S23_Ultra_xy41rj.jpg",
    },
    {
        name: "Google Pixel 8 Pro",
        category: "mobiles",
        specifications: {
            storage: "256GB",
            display: "6.7-inch LTPO OLED",
            camera: "50MP Octa PD",
            processor: "Google Tensor G3",
            warranty: "1 Year Google Warranty",
        },
        price: 109999,
        originalPrice: 119999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743518194/Google_Pixel_8_Pro_drxgca.jpg",
    },
    {
        name: "OnePlus 12",
        category: "mobiles",
        specifications: {
            storage: "256GB",
            display: "6.82-inch LTPO AMOLED",
            camera: "50MP Main Camera",
            processor: "Snapdragon 8 Gen 3",
            warranty: "1 Year OnePlus Warranty",
        },
        price: 64999,
        originalPrice: 69999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743518193/OnePlus_12_siihu5.jpg",
    },
    {
        name: "Xiaomi 14 Pro",
        category: "mobiles",
        specifications: {
            storage: "512GB",
            display: "6.73-inch AMOLED",
            camera: "50MP Main Camera",
            processor: "Snapdragon 8 Gen 3",
            warranty: "1 Year Xiaomi Warranty",
        },
        price: 79999,
        originalPrice: 84999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743518193/Xiaomi_14_Pro_x2pm2p.jpg",
    },
    {
        name: "Motorola Edge 40 Pro",
        category: "mobiles",
        specifications: {
            storage: "256GB",
            display: "6.67-inch pOLED",
            camera: "50MP Main Camera",
            processor: "Snapdragon 8 Gen 2",
            warranty: "1 Year Motorola Warranty",
        },
        price: 54999,
        originalPrice: 59999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743518193/Motorola_Edge_40_Pro_s6knz0.png",
    },
    {
        name: "Realme GT 5 Pro",
        category: "mobiles",
        specifications: {
            storage: "256GB",
            display: "6.78-inch AMOLED",
            camera: "50MP Main Camera",
            processor: "Snapdragon 8 Gen 3",
            warranty: "1 Year Realme Warranty",
        },
        price: 49999,
        originalPrice: 54999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743518193/Realme_GT_5_Pro_prlpdv.jpg",
    },
    {
        name: "Vivo X100 Pro",
        category: "mobiles",
        specifications: {
            storage: "512GB",
            display: "6.78-inch AMOLED",
            camera: "50MP Main Camera",
            processor: "Dimensity 9300",
            warranty: "1 Year Vivo Warranty",
        },
        price: 89999,
        originalPrice: 94999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743518196/Vivo_X100_Pro_qjxsfc.jpg",
    },
    {
        name: "Oppo Find X7 Ultra",
        category: "mobiles",
        specifications: {
            storage: "256GB",
            display: "6.82-inch AMOLED",
            camera: "50MP Main Camera",
            processor: "Snapdragon 8 Gen 3",
            warranty: "1 Year Oppo Warranty",
        },
        price: 94999,
        originalPrice: 99999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743666597/Oppo_Find_X7_Ultra_tpekdp.jpg",
    },
    {
        name: "Nothing Phone (2)",
        category: "mobiles",
        specifications: {
            storage: "256GB",
            display: "6.7-inch LTPO OLED",
            camera: "50MP Main Camera",
            processor: "Snapdragon 8+ Gen 1",
            warranty: "1 Year Nothing Warranty",
        }, 
        price: 44999,
        originalPrice: 49999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743666598/Nothing_Phone_2_wy1tpg.jpg",
    },
    // Laptops
    {
        name: "MacBook Air M2",
        category: "laptops",
        specifications: {
            display: "13.6-inch Liquid Retina",
            processor: "Apple M2 chip",
            storage: "512GB SSD",
            battery: "Up to 18 hours",
            warranty: "1 Year Apple Warranty",
        },
        price: 114999,
        originalPrice: 124999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743512325/MacBook_Air_M2_demdtc.jpg",
    },
    {
        name: "Dell XPS 13 Plus",
        category: "laptops",
        specifications: {
            display: "13.4-inch OLED",
            processor: "Intel Core i7",
            storage: "1TB SSD",
            memory: "32GB RAM",
            warranty: "1 Year Dell Warranty",
        },
        price: 149999,
        originalPrice: 159999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743518959/Dell_XPS_13_Plus_kp2elb.jpg",
    },
    {
        name: "HP Spectre x360",
        category: "laptops",
        specifications: {
            display: "13.5-inch OLED Touchscreen",
            processor: "Intel Core i7",
            storage: "1TB SSD",
            memory: "16GB RAM",
            warranty: "1 Year HP Warranty",
        },
        price: 139999,
        originalPrice: 149999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743518958/HP_Spectre_x360_d58cfa.jpg",
    },
    {
        name: "Lenovo ThinkPad X1 Carbon Gen 11",
        category: "laptops",
        specifications: {
            display: "14-inch IPS",
            processor: "Intel Core i7",
            storage: "1TB SSD",
            memory: "32GB RAM",
            warranty: "1 Year Lenovo Warranty",
        },
        price: 154999,
        originalPrice: 164999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743518959/Lenovo_ThinkPad_X1_Carbon_Gen_11_mskyos.jpg",
    },
    {
        name: "ASUS ROG Zephyrus G14",
        category: "laptops",
        specifications: {
            display: "14-inch QHD",
            processor: "AMD Ryzen 9",
            storage: "1TB SSD",
            memory: "16GB RAM",
            warranty: "1 Year ASUS Warranty",
        },
        price: 129999,
        originalPrice: 139999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743665220/ASUS_ROG_Zephyrus_G14_jjgyow.jpg",
    },
    {
        name: "Microsoft Surface Laptop 5",
        category: "laptops",
        specifications: {
            display: "13.5-inch PixelSense",
            processor: "Intel Core i5",
            storage: "512GB SSD",
            memory: "16GB RAM",
            warranty: "1 Year Microsoft Warranty",
        },
        price: 109999,
        originalPrice: 119999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743665221/Microsoft_Surface_Laptop_5_f8uxef.jpg",
    },
    {
        name: "Acer Swift X",
        category: "laptops",
        specifications: {
            display: "14-inch IPS",
            processor: "AMD Ryzen 7",
            storage: "512GB SSD",
            memory: "16GB RAM",
            warranty: "1 Year Acer Warranty",
        },
        price: 89999,
        originalPrice: 99999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743665221/Acer_Swift_X_iqlixx.jpg",
    },
    {
        name: "LG Gram 17",
        category: "laptops",
        specifications: {
            display: "17-inch IPS",
            processor: "Intel Core i7",
            storage: "1TB SSD",
            memory: "16GB RAM",
            warranty: "1 Year LG Warranty",
        },
        price: 124999,
        originalPrice: 134999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743665220/LG_Gram_17_epjakp.jpg",
    },
    {
        name: "Razer Blade 15",
        category: "laptops",
        specifications: {
            display: "15.6-inch QHD",
            processor: "Intel Core i9",
            storage: "1TB SSD",
            memory: "32GB RAM",
            warranty: "1 Year Razer Warranty",
        },
        price: 179999,
        originalPrice: 189999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743665220/Razer_Blade_15_rd9hmk.jpg",
    },
    {
        name: "Samsung Galaxy Book3 Ultra",
        category: "laptops",
        specifications: {
            display: "16-inch AMOLED",
            processor: "Intel Core i9",
            storage: "1TB SSD",
            memory: "32GB RAM",
            warranty: "1 Year Samsung Warranty",
        },
        price: 169999,
        originalPrice: 179999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743665221/Samsung_Galaxy_Book3_Ultra_euipos.jpg",
    },
    // Dresses
    {
        name: "Elegant Evening Gown",
        category: "dresses",
        specifications: {
            material: "Silk",
            style: "Maxi",
            color: "Navy Blue",
            size: "M",
        },
        price: 7999,
        originalPrice: 8999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743668304/Elegant_Evening_Gown_hviemz.jpg",
    },
    {
        name: "Casual Summer Dress",
        category: "dresses",
        specifications: {
            material: "Cotton",
            style: "Sundress",
            color: "Floral Print",
            size: "S",
        },
        price: 2499,
        originalPrice: 2999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743668303/Casual_Summer_Dress_wusb9p.jpg",
    },
    {
        name: "Formal Business Dress",
        category: "dresses",
        specifications: {
            material: "Polyester Blend",
            style: "Sheath Dress",
            color: "Black",
            size: "L",
        },
        price: 4999,
        originalPrice: 5499,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743668302/Formal_Business_Dress_xkbh6o.jpg",
    },
    {
        name: "Bohemian Maxi Dress",
        category: "dresses",
        specifications: {
            material: "Rayon",
            style: "Maxi",
            color: "Multi-colored",
            size: "M",
        },
        price: 3999,
        originalPrice: 4499,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743668301/Bohemian_Maxi_Dress_lcnvof.jpg",
    },
    {
        name: "Lace Cocktail Dress",
        category: "dresses",
        specifications: {
            material: "Lace",
            style: "Cocktail",
            color: "Red",
            size: "S",
        },
        price: 5999,
        originalPrice: 6499,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743668299/Lace_Cocktail_Dress_wxwa7y.jpg",
    },
    {
        name: "Denim Shirt Dress",
        category: "dresses",
        specifications: {
            material: "Denim",
            style: "Shirt Dress",
            color: "Blue",
            size: "M",
        },
        price: 3499,
        originalPrice: 3999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743668298/Denim_Shirt_Dress_xugrxc.jpg",
    },
    {
        name: "Velvet Party Dress",
        category: "dresses",
        specifications: {
            material: "Velvet",
            style: "Mini Dress",
            color: "Emerald Green",
            size: "L",
        },
        price: 6999,
        originalPrice: 7499,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743668296/Velvet_Party_Dress_lpe2m3.jpg",
    },
    {
        name: "Knitted Sweater Dress",
        category: "dresses",
        specifications: {
            material: "Wool Blend",
            style: "Sweater Dress",
            color: "Beige",
            size: "M",
        },
        price: 4499,
        originalPrice: 4999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743668295/Knitted_Sweater_Dress_beyjcs.jpg",
    },
    {
        name: "Silk Wrap Dress",
        category: "dresses",
        specifications: {
            material: "Silk",
            style: "Wrap Dress",
            color: "Pink",
            size: "S",
        },
        price: 5499,
        originalPrice: 5999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743668297/Silk_Wrap_Dress_bbiev8.jpg",
    },
    {
        name: "Printed Tunic Dress",
        category: "dresses",
        specifications: {
            material: "Cotton Blend",
            style: "Tunic Dress",
            color: "Aztec Print",
            size: "L",
        },
        price: 2999,
        originalPrice: 3499,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743668296/Printed_Tunic_Dress_ehcnuj.png",
    },
    // Accessories
    {
        name: "Sony WH-1000XM5",
        category: "accessories",
        specifications: {
            type: "Over-Ear Wireless Headphones",
            noiseCancellation: "Industry-Leading ANC",
            battery: "30 Hours",
            warranty: "1 Year Sony Warranty",
        },
        price: 29999,
        originalPrice: 34999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743512326/Sony_WH-1000XM5_m38ke8.jpg",
    },
    {
        name: "Apple Watch Series 9",
        category: "accessories",
        specifications: {
            type: "Smartwatch",
            display: "Always-On Retina",
            features: "GPS, Heart Rate Monitor",
            warranty: "1 Year Apple Warranty",
        },
        price: 39999,
        originalPrice: 44999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743669665/Apple_Watch_Series_9_ehe591.jpg",
    },
    {
        name: "Ray-Ban Aviator Sunglasses",
        category: "accessories",
        specifications: {
            type: "Sunglasses",
            frame: "Metal",
            lens: "UV Protection",
            warranty: "1 Year Ray-Ban Warranty",
        },
        price: 14999,
        originalPrice: 16999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743669663/Ray-Ban_Aviator_Sunglasses_rycfpf.jpg",
    },
    {
        name: "Michael Kors Leather Tote Bag",
        category: "accessories",
        specifications: {
            type: "Tote Bag",
            material: "Leather",
            color: "Black",
            size: "Large",
        },
        price: 24999,
        originalPrice: 27999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743669662/Michael_Kors_Leather_Tote_Bag_pk0j4s.png",
    },
    {
        name: "Fitbit Charge 6",
        category: "accessories",
        specations: {
            type: "Fitness Tracker",
            features: "GPS, Heart Rate, SpO2",
            battery: "7 Days",
            warranty: "1 Year Fitbit Warranty",
        },
        price: 12999,
        originalPrice: 14999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743669660/41M_F43gRJL._AC_UF1000_1000_QL80__kjnim8.jpg",
    },
    {
        name: "Pandora Charm Bracelet",
        category: "accessories",
        specifications: {
            type: "Bracelet",
            material: "Sterling Silver",
            charms: "Customizable",
            warranty: "1 Year Pandora Warranty",
        },
        price: 19999,
        originalPrice: 22999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743669658/Pandora_Charm_Bracelet_ptxtav.jpg",
    },
    {
        name: "Casio G-Shock Watch",
        category: "accessories",
        specifications: {
            type: "Digital Watch",
            features: "Shock Resistant, Water Resistant",
            warranty: "1 Year Casio Warranty",
        },
        price: 9999,
        originalPrice: 11999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743669658/Casio_G-Shock_Watch_kyajo7.jpgg",
    },
    {
        name: "Silk Scarf",
        category: "accessories",
        specifications: {
            type: "Scarf",
            material: "Silk",
            color: "Patterned",
            size: "Large",
        },
        price: 4999,
        originalPrice: 5499,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743669659/Silk_Scarf_eegl6z.jpg",
    },
    {
        name: "Leather Wallet",
        category: "accessories",
        specifications: {
            type: "Wallet",
            material: "Leather",
            color: "Brown",
            features: "Card Slots, Coin Pocket",
        },
        price: 6999,
        originalPrice: 7999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743669657/Leather_Wallet_n7u9o6.jpg",
    },
    {
        name: "Beats Studio Buds+",
        category: "accessories",
        specifications: {
            type: "True Wireless Earbuds",
            noiseCancellation: "Active Noise Cancellation",
            battery: "Up to 36 hours",
            warranty: "1 Year Beats Warranty",
        },
        price: 16999,
        originalPrice: 19999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743669666/Beats_Studio_Buds_pykwyq.jpg",
    },
    // Shoes
    {
        name: "Nike Running Shoes",
        category: "shoes",
        specifications: {
            material: "Mesh & Rubber",
            weight: "Lightweight",
            sole: "Cushioned Sole",
        },
        price: 5999,
        originalPrice: 6999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743512326/Nike_Running_Shoes_q7bcag.jpg",
    },
    {
        name: "Adidas Ultraboost DNA",
        category: "shoes",
        specifications: {
            material: "Primeknit",
            weight: "Lightweight",
            sole: "Boost Technology",
        },
        price: 7499,
        originalPrice: 8499,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743678077/Adidas_Ultraboost_DNA_jjp8q7.jpg",
    },
    {
        name: "Dr. Martens 1460 Boots",
        category: "shoes",
        specifications: {
            material: "Leather",
            style: "Ankle Boots",
            sole: "AirWair",
        },
        price: 9999,
        originalPrice: 11999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743678074/Dr._Martens_1460_Boots_kppjal.jpg",
    },
    {
        name: "Converse Chuck Taylor All Star",
        category: "shoes",
        specifications: {
            material: "Canvas",
            style: "High Top",
            sole: "Rubber",
        },
        price: 3999,
        originalPrice: 4499,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743678073/Converse_Chuck_Taylor_All_Star_ddiou6.jpg",
    },
    {
        name: "Puma RS-X3 Sneakers",
        category: "shoes",
        specifications: {
            material: "Mesh & Leather",
            style: "Chunky Sneakers",
            sole: "RS Technology",
        },
        price: 6499,
        originalPrice: 7499,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743678073/Converse_Chuck_Taylor_All_Star_ddiou6.jpg",
    },
    {
        name: "New Balance 574 Classics",
        category: "shoes",
        specifications: {
            material: "Suede & Mesh",
            style: "Low Top",
            sole: "ENCAP",
        },
        price: 5499,
        originalPrice: 6499,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743678068/New_Balance_574_Classics_gtzvvb.jpg",
    },
    {
        name: "Vans Old Skool",
        category: "shoes",
        specifications: {
            material: "Canvas & Suede",
            style: "Low Top",
            sole: "Waffle Rubber",
        },
        price: 4499,
        originalPrice: 4999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743678069/Vans_Old_Skool_xeatnx.jpg",
    },
    {
        name: "Timberland Premium Boots",
        category: "shoes",
        specifications: {
            material: "Waterproof Leather",
            style: "Work Boots",
            sole: "Rubber Lug",
        },
        price: 10999,
        originalPrice: 12999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743678068/Timberland_Premium_Boots_af1q4x.jpg",
    },
    {
        name: "Reebok Classic Leather",
        category: "shoes",
        specifications: {
            material: "Leather",
            style: "Low Top",
            sole: "Rubber",
        },
        price: 4999,
        originalPrice: 5999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743678081/Reebok_Classic_Leather_ufcn55.jpg",
    },
    {
        name: "ASICS Gel-Kayano 28",
        category: "shoes",
        specifications: {
            material: "Mesh",
            style: "Running Shoes",
            sole: "Gel Technology",
        },
        price: 8999,
        originalPrice: 9999,
        image: "https://res.cloudinary.com/dewfnihiq/image/upload/v1743678078/ASICS_Gel-Kayano_28_tujswb.jpg",
    },
];

const seedProducts = async () => {
    try {
        await Product.deleteMany(); // Remove old data
        await Product.insertMany(products); // Insert new products
        console.log("Database seeded successfully!");
        mongoose.connection.close();
    } catch (error) {
        console.error("Error seeding database:", error);
    }
};

seedProducts();
